version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      day: "monday"
      interval: "weekly"
      time: "03:00"
      timezone: "Asia/Kuala_Lumpur"

    groups:
      grammy:
        applies-to: version-updates
        patterns:
          - "*grammy*"
